version: '3'
services:
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "80:80"
    profiles:
      - dependencies
  backend:
    build:
      context: ./apps/backend
    ports:
      - "3000:3000"
    profiles:
      - dependencies
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - "5432:5432"
    profiles:
      - dependencies
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
    ports:
      - "8080:80"
    profiles:
      - tools

