version: '3'
services:
  frontend:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx serve frontend --host=0.0.0.0
    ports:
      - 4200:4200
    profiles:
      - dependencies
  backend:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npx nx serve backend --host=0.0.0.0
    ports:
      - 3000:3000
      - 9229:9229
    profiles:
      - dependencies
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - "5432:5432"
    profiles:
      - dependencies
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
    ports:
      - "8080:80"
    profiles:
      - tools

volumes:
  mono-node-modules: null